version: '3.7'
  
volumes:
  alfa5_rabbitmq:
networks:
  alfa5:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.7-management-alpine
    volumes:
      - alfa5_rabbitmq:/var/lib/rabbitmq
    networks:
      - alfa5
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    container_name: redis
    image: redis:7.2.2-alpine
    networks:
      - alfa5
    ports:
      - "6379:6379"
