name: Deploy Entire App using Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish ./src/Alfa5.AuthServer/Alfa5.AuthServer.csproj -c Release -o ./publish/AuthServer
          dir ./publish/AuthServer
          
      - name: Deploy AuthServer using Web Deploy
        uses: cschleiden/webdeploy-action@v1
        with:
          package: ./publish/AuthServer
          webSiteName: 'webdepauthserveralfa5' 
          publishProfile: ./publish/webdepauthserveralfa5.PublishSettings 

      - name: Check Deployment Success
        run: |
          if ($LASTEXITCODE -ne 0) {
            exit 1
          }