name: Deploy Entire App using Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release 

    - name: Publish AuthServer
      run: dotnet publish ./src/Alfa5.AuthServer/Alfa5.AuthServer.csproj -c Release -o ./publish/AuthServer
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-output
        path: ./publish/AuthServer
    
    - name: List published files
      run: dir ./publish/AuthServer

    - name: Deploy AuthServer using Web Deploy
    - uses: actions/download-artifact@v3
      with:
        name: publish-output
        path: ./publish/AuthServer

    - name: Use Web Deploy to deploy
      uses: cschleiden/webdeploy-action@v1
      with:
        package: ./publish/AuthServer
        publish-profile: ./publish/webdepauthserveralfa5.PublishSettings

    