name: Deploy Entire App using Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release 

    - name: Publish AuthServer
      run: dotnet publish ./src/Alfa5.AuthServer/Alfa5.AuthServer.csproj -c Release -o ./publish/AuthServer

    - name: List published files
      run: dir ./publish/AuthServer

    - name: Deploy AuthServer using Web Deploy
      run: |
        & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" \
          -verb:sync \
          -source:contentPath="./publish/AuthServer" \
          -dest:computerName="https://52.168.74.165:8172/msdeploy.axd",siteName="webdepauthserveralfa5",username="sdtweb01\opsadmin",password="AbacateDoce@01",authType=Basic \
          -allowUntrusted

    - name: Publish Blazor
      run: dotnet publish ./src/Alfa5.Blazor/Alfa5.Blazor.csproj -c Release -o ./publish/Blazor

    - name: Deploy Blazor using Web Deploy
      run: |
        & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
        -verb:sync `
        -source:contentPath=./publish/Blazor `
        -dest:iisApp=webdepblazoralfa5,wmsvc=https://52.168.74.165:8172/msdeploy.axd,username=sdtweb01\opsadmin,password=AbacateDoce@01,authType=Basic `
        -allowUntrusted

    - name: Publish HttpApiHost
      run: dotnet publish ./src/Alfa5.HttpApi.Host/Alfa5.HttpApi.Host.csproj -c Release -o ./publish/HttpApi.Host

    - name: Deploy HttpApiHost using Web Deploy
      run: |
        & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
        -verb:sync `
        -source:contentPath=./publish/HttpApi.Host `
        -dest:iisApp=webdephttpapihostalfa5,wmsvc=https://52.168.74.165:8172/msdeploy.axd,username=sdtweb01\opsadmin,password=AbacateDoce@01,authType=Basic `
        -allowUntrusted
